name: my_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  animated_text_kit: ^4.3.0
  flutter:
    sdk: flutter
  hugeicons: ^1.1.7
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/quicksand/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets\fonts\quicksand\Quicksand-Light.ttf
          style: normal
          weight: 300
        - asset: assets\fonts\quicksand\Quicksand-Regular.ttf
          style: normal
          weight: 400
        - asset: assets\fonts\quicksand\Quicksand-Medium.ttf
          style: normal
          weight: 500
        - asset: assets\fonts\quicksand\Quicksand-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets\fonts\quicksand\Quicksand-Bold.ttf
          style: normal
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets\fonts\poppins\Poppins-Light.ttf
          style: normal
          weight: 300
        - asset: assets\fonts\poppins\Poppins-Regular.ttf
          style: normal
          weight: 400
        - asset: assets\fonts\poppins\Poppins-Italic.ttf
          style: italic
          weight: 400
        - asset: assets\fonts\poppins\Poppins-Medium.ttf
          style: normal
          weight: 500
        - asset: assets\fonts\poppins\Poppins-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets\fonts\poppins\Poppins-Bold.ttf
          style: normal
          weight: 700
